config/routes.rb
Rails.application.routes.draw do

  resources :student_mcqs

  devise_for :admins , :controllers => {sessions:'sessions'}
  devise_for :instructors , :controllers => {sessions:'sessions'}
  devise_for :students , :controllers => {sessions:'sessions'}

  devise_scope :student do
    get "/sign_in" => "sessions#new"
    post "/sign_in" => "sessions#create"
    delete "/sign_out" => "sessions#destroy"
  end
  
  get 'quizzes/quiz_statistics'

  post 'sessions/authorize'

  get 'quizzes/prev_quizzes'

  get 'quizzes/student_statistics'
  
  resources :instructors

  resources :quizzes

  resources :students

  root 'students#index'

end

app/models/student_mcq.rb
class StudentMcq < ActiveRecord::Base

    ######################## Relations ########################

	belongs_to :student
	belongs_to :mcq

end

app/controllers/student_mcqs_controller.rb
class StudentMcqsController < ApplicationController
  before_action :set_student_mcq, only: [:show, :edit, :update, :destroy]

  # GET /student_mcqs
  # GET /student_mcqs.json
  def index
    @student_mcqs = StudentMcq.all
  end

  # GET /student_mcqs/1
  # GET /student_mcqs/1.json
  def show
  end

  # GET /student_mcqs/new
  def new
    @student_mcq = StudentMcq.new
  end

  # GET /student_mcqs/1/edit
  def edit
  end

  # POST /student_mcqs
  # POST /student_mcqs.json
  
 def create
    @quiz_id1 =  params["quiz_id"]

    if StudentQuiz.find_by(student_id: current_student.id, quiz_id: @quiz_id1)
      render :template=>"student_mcqs/new.json.jbuilder", :status=> :unauthorized, 
      :formats => [:json]
    end

    @mcqs1 = Mcq.where(quiz_id: @quiz_id1)
    @grade = 0
    params["answers"].each_index do |i|   
        @stu_mcq = StudentMcq.new
        @stu_mcq.student_answer = params["answers"][i]
        @stu_mcq.mcq_id = @mcqs1[i].id
        @stu_mcq.student_id = current_student.id

        if @stu_mcq[:student_answer] == @mcqs1[i][:answer].to_i
        
         @grade = @grade + @mcqs1[i][:question_mark]
        end
    end

    StudentQuiz.create(student_quiz_mark: @grade, student_id: current_student.id, quiz_id: @quiz_id1)

     render :template=>"student_mcqs/new.json.jbuilder", :status=> :created, 
     locals: {grade: @grade},
     :formats => [:json]
  end

  # PATCH/PUT /student_mcqs/1
  # PATCH/PUT /student_mcqs/1.json
  def update
    respond_to do |format|
      if @student_mcq.update(student_mcq_params)
        format.html { redirect_to @student_mcq, notice: 'Student mcq was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_mcq }
      else
        format.html { render :edit }
        format.json { render json: @student_mcq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_mcqs/1
  # DELETE /student_mcqs/1.json
  def destroy
    @student_mcq.destroy
    respond_to do |format|
      format.html { redirect_to student_mcqs_url, notice: 'Student mcq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_mcq
      @student_mcq = StudentMcq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_mcq_params
      params[:student_mcq]
    end
end

app/helpers/student_mcqs_helper.rb
module StudentMcqsHelper
end

app/views/student_mcqs/_form.html.erb
<%= form_for(@student_mcq) do |f| %>
  <% if @student_mcq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_mcq.errors.count, "error") %> prohibited this student_mcq from being saved:</h2>

      <ul>
      <% @student_mcq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_mcqs/edit.html.erb
<h1>Editing Student Mcq</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_mcq %> |
<%= link_to 'Back', student_mcqs_path %>

app/views/student_mcqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Student Mcqs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_mcqs.each do |student_mcq| %>
      <tr>
        <td><%= link_to 'Show', student_mcq %></td>
        <td><%= link_to 'Edit', edit_student_mcq_path(student_mcq) %></td>
        <td><%= link_to 'Destroy', student_mcq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student mcq', new_student_mcq_path %>

app/views/student_mcqs/new.html.erb
)

app/views/student_mcqs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_student_mcq_path(@student_mcq) %> |
<%= link_to 'Back', student_mcqs_path %>