config/routes.rb
Rails.application.routes.draw do

  resources :student_mcqs

  devise_for :admins , :controllers => {sessions:'sessions'}
  devise_for :instructors , :controllers => {sessions:'sessions'}
  devise_for :students , :controllers => {sessions:'sessions'}

  devise_scope :student do
    get "/sign_in" => "sessions#new"
    post "/sign_in" => "sessions#create"
    delete "/sign_out" => "sessions#destroy"
  end
  
  get 'quizzes/quiz_statistics'

  post 'sessions/authorize'

  get 'quizzes/prev_quizzes'

  get 'quizzes/student_statistics'
  
  resources :instructors

  resources :quizzes

  resources :students

  root 'students#index'

end

app/controllers/student_quizzes_controller.rb
class StudentQuizzesController < ApplicationController
  before_action :set_student_quiz, only: [:show, :edit, :update, :destroy]

  # GET /student_quizzes
  # GET /student_quizzes.json
  def index
    @student_quizzes = StudentQuiz.all
  end

  # GET /student_quizzes/1
  # GET /student_quizzes/1.json
  def show
  end

  # GET /student_quizzes/new
  def new
    @student_quiz = StudentQuiz.new
  end

  # GET /student_quizzes/1/edit
  def edit
  end

  # POST /student_quizzes
  # POST /student_quizzes.json
  def create

    # quiz_id1,grade is passed from the student mcq contoller #create
    # q[:g]and q[:quiz__id]
    
    StudentQuiz.create(student_quiz_mark: q[:g], student_id: current_student.id, quiz_id: q[:quiz_id])


  end

    
  

  # PATCH/PUT /student_quizzes/1
  # PATCH/PUT /student_quizzes/1.json
  def update
    respond_to do |format|
      if @student_quiz.update(student_quiz_params)
        format.html { redirect_to @student_quiz, notice: 'Student quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_quiz }
      else
        format.html { render :edit }
        format.json { render json: @student_quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_quizzes/1
  # DELETE /student_quizzes/1.json
  def destroy
    @student_quiz.destroy
    respond_to do |format|
      format.html { redirect_to student_quizzes_url, notice: 'Student quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_quiz
      @student_quiz = StudentQuiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_quiz_params
      params[:student_quiz]
    end


end

app/helpers/student_quizzes_helper.rb
module StudentQuizzesHelper
end

app/views/student_quizzes/_form.html.erb
<%= form_for(@student_quiz) do |f| %>
  <% if @student_quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_quiz.errors.count, "error") %> prohibited this student_quiz from being saved:</h2>

      <ul>
      <% @student_quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_quizzes/edit.html.erb
<h1>Editing Student Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_quiz %> |
<%= link_to 'Back', student_quizzes_path %>

app/views/student_quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Student Quizzes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_quizzes.each do |student_quiz| %>
      <tr>
        <td><%= link_to 'Show', student_quiz %></td>
        <td><%= link_to 'Edit', edit_student_quiz_path(student_quiz) %></td>
        <td><%= link_to 'Destroy', student_quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student quiz', new_student_quiz_path %>

app/views/student_quizzes/new.html.erb
<h1>New Student Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', student_quizzes_path %>

app/views/student_quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_student_quiz_path(@student_quiz) %> |
<%= link_to 'Back', student_quizzes_path %>